### ISSUE TITLE
[BUG]Contributer's programme banner missing hyperlink

### ISSUE THREAD

**Issue by Ghat0tkach** [pluralsh/plural#1101]
## Summary

Whenever the contributer's programme banner appears , the link leads to the blog of cluster management

## Reproduction

Visit on this [page](https://www.plural.sh/applications/redis)
Click on the contributor's programme page

## Plural UI/UX Issue Screenshots

![image](https://github.com/pluralsh/plural/assets/59855919/46740466-731c-4f63-88ce-c259b1a5eb61)

## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by dogmar** [comment]
All fixed. Thanks for letting us know!
