### ISSUE TITLE
Security information are not correct

### ISSUE THREAD

**Issue by svennergr** [pluralsh/plural#1174]
## Summary

The file at https://github.com/pluralsh/plural/blob/master/SECURITY.md points to https://hackerone.com/plural which leads to a "not found" error. Also the email support@plural.sh is responding with 

```
We're writing to let you know that the group you tried to contact (support) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.
```

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by svennergr** [comment]
@michaeljguarino @samweaver I'd appreciate a way to responsible disclose a vulnerability.

**Comment by asmallberg** [comment]
Hey @svennergr could you try support@plural.sh at email again? Also if you have a HackerOne profile I can invite you.

**Comment by svennergr** [comment]
> Hey @svennergr could you try [support@plural.sh](mailto:support@plural.sh) again? Also if you have a HackerOne profile I can invite you.

Thanks @asmallberg. Message sent and it looks like it's not erroring out this time 👍

**Comment by svennergr** [comment]
Thanks, reported. This can be closed.
