### ISSUE TITLE
Add Kestra to the marketplace

### ISSUE THREAD

**Issue by anna-geller** [pluralsh/plural#1201]
Hi!

It would be great to add Kestra to the catalog. There is a ready-to-use [Helm chart](https://helm.kestra.io/).

- the source code of the charts can be found in the [kestra-io/helm-charts](https://github.com/kestra-io/helm-charts) repo.
- and here is [K8s deployment documentation](https://kestra.io/docs/administrator-guide/deployment/kubernetes).

Happy to help provide any additional info - feel free to ping me on [Slack](https://kestra.io/slack).

**Comment by michaeljguarino** [comment]
Hey @anna-geller would you mind moving this to https://github.com/pluralsh/plural-artifacts?

**Comment by anna-geller** [comment]
https://github.com/pluralsh/plural-artifacts/issues/812
