### ISSUE TITLE
Bring your own oauth/sso for installed applications

### ISSUE THREAD

**Issue by ncbkr** [pluralsh/plural#164]
## Use Case

As a provider of an application, I want to use my own OIDC provider for controlling user access to my application. I do not want to onboard all application users to my plural account.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by michaeljguarino** [comment]
We now have SSO support added to the platform.  It requires manual configuration, but if you reach out to us, we can add it to an account pretty easily.
