### ISSUE TITLE
AWS: Autoscaler provisions Spot instances even though pending pods have no toleration

### ISSUE THREAD

**Issue by ncbkr** [pluralsh/plural#165]
## Summary

When a pending pod cannot be scheduled on existing nodes, the autoscaler always provisions a new spot instance. Even if the pending pod has no toleration for spot instances. This results in the pod remaining in state pending.

I expect the autoscaler to know it should not provision a spot instance if the pod does not have the respective toleration.

## Reproduction

Via the Kubeflow Dashboard, I created 4-6 Jupyter Notebooks with high resource requests (2CPUs, 12GB RAM, no GPU). The autoscaler provisioned multiple GPU spot instances.

Here is a documentation of what I observed:

-   **2022-02-09 10:20 start**

    ![initial-nodes](https://user-images.githubusercontent.com/70146154/153253694-02f890af-ee92-49f2-b7cb-cb3c4e8a9849.png)

-   **2022-02-09 10:20 starting cpu notebooks with high resource requests (4 new notebooks. each 2 cpus and 12 gb of memory)**

    ![pods-cannot-be-scheduled](https://user-images.githubusercontent.com/70146154/153253803-6bb704f9-b7d2-4d82-8e29-1b3d389c5c87.png)

-   **Logs from the bootstrap application in the plural console**

    ```sh
    2022-02-09T10:27:20+01:00
    I0209 09:27:20.609195       1 filter_out_schedulable.go:170] 0 pods were kept as unschedulable based on caching
    2022-02-09T10:27:20+01:00
    I0209 09:27:20.609185       1 filter_out_schedulable.go:157] Pod nico-becker.cpu-2-mem-12-04-0 marked as unschedulable can be scheduled on node template-node-for-eks-at-onplural-sh-gpu-medium-spot-c4bf3c1b-8046-7c75-639d-f6d403ffb159-4971494515820000129-0. Ignoring in scale up.
    2022-02-09T10:27:20+01:00
    I0209 09:27:20.609175       1 scheduler_binder.go:892] Provisioning for 1 claims of pod "nico-becker/cpu-2-mem-12-04-0" that has no matching volumes on node "template-node-for-eks-at-onplural-sh-gpu-medium-spot-c4bf3c1b-8046-7c75-639d-f6d403ffb159-4971494515820000129-0" ...
    2022-02-09T10:27:20+01:00
    I0209 09:27:20.609160       1 scheduler_binder.go:828] No matching volumes for Pod "nico-becker/cpu-2-mem-12-04-0", PVC "nico-becker/workspace-cpu-2-mem-12-04" on node "template-node-for-eks-at-onplural-sh-gpu-medium-spot-c4bf3c1b-8046-7c75-639d-f6d403ffb159-4971494515820000129-0"
    2022-02-09T10:27:20+01:00
    I0209 09:27:20.609058       1 filter_out_schedulable.go:157] Pod nico-becker.cpu-2-mem-12-03-0 marked as unschedulable can be scheduled on node template-node-for-eks-at-onplural-sh-gpu-medium-spot-c4bf3c1b-8046-7c75-639d-f6d403ffb159-4971494515820000129-0. Ignoring in scale up.
    2022-02-09T10:27:20+01:00
    I0209 09:27:20.608984       1 scheduler_binder.go:892] Provisioning for 1 claims of pod "nico-becker/cpu-2-mem-12-03-0" that has no matching volumes on node "template-node-for-eks-at-onplural-sh-gpu-medium-spot-c4bf3c1b-8046-7c75-639d-f6d403ffb159-4971494515820000129-0" ...
    2022-02-09T10:27:20+01:00
    I0209 09:27:20.608938       1 scheduler_binder.go:828] No matching volumes for Pod "nico-becker/cpu-2-mem-12-03-0", PVC "nico-becker/workspace-cpu-2-mem-12-03" on node "template-node-for-eks-at-onplural-sh-gpu-medium-spot-c4bf3c1b-8046-7c75-639d-f6d403ffb159-4971494515820000129-0"
    2022-02-09T10:27:20+01:00
    I0209 09:27:20.608764       1 filter_out_schedulable.go:157] Pod nico-becker.cpu-2-mem-12-02-0 marked as unschedulable can be scheduled on node template-node-for-eks-at-onplural-sh-gpu-medium-spot-c4bf3c1b-8046-7c75-639d-f6d403ffb159-4971494515820000129-0. Ignoring in scale up.
    2022-02-09T10:27:20+01:00
    I0209 09:27:20.608709       1 scheduler_binder.go:892] Provisioning for 1 claims of pod "nico-becker/cpu-2-mem-12-02-0" that has no matching volumes on node "template-node-for-eks-at-onplural-sh-gpu-medium-spot-c4bf3c1b-8046-7c75-639d-f6d403ffb159-
    ```

-   **2022-02-09 10:44 new nodes present**

    ![new-nodes](https://user-images.githubusercontent.com/70146154/153254107-46d08380-1882-439f-8d44-05cd0b51ccf8.png)

-   **2022-02-09 12:10 5 spot instance, but pods can't be scheduled**

    ![pods-still-cannot-be-scheduled](https://user-images.githubusercontent.com/70146154/153254182-b9ed703a-0be5-477d-80b8-e36b09f2a72b.png)

-   **2022-02-09 12:10 start deletion of pending notebooks**

-   **2022-02-09 12:30 nodes scaled down again**

For a later attempt, I also extracted the scheduler logs from the control plane:

-   [node-scheduler.csv](https://github.com/pluralsh/plural/files/8034835/node-scheduler.csv)
-   [pod-scheduler.csv](https://github.com/pluralsh/plural/files/8034836/pod-scheduler.csv)

## Additional Info about Your Environment

Plural managed EKS clusert with Kubeflow installed.

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by michaeljguarino** [comment]
Could we move this bug to the plural-artifacts repo?  The autoscaler configuration lives in the bootstrap app there.

**Comment by DavidSpek** [comment]
I don't think we've seen this since so closing the issue.
