### ISSUE TITLE
Allow plural artifact registration from non-plural git repositories

### ISSUE THREAD

**Issue by jaystary** [pluralsh/plural#168]
## Use Case
It would be useful, to be able to publish plural artifacts to the catalogue from random git repositories instead of just plural repos. In that case, owners of an application could natively extend their repos to include the deployment instructions wrapped into a CICD pipeline.

## Ideas of Implementation
- Set up a template including Readme that lays out the process how to publish a artifact
- Init new git repo and wrap code + add publishing instructions
- Trigger deployment to plural via github actions e.g. - make sure that artifact is valid by running a set of validations against it (or maybe even provide a sandbox environment against which new artifacts can be validated against)

There should be a flag that can be set to publish it to the public / private catalogue 

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

**Comment by michaeljguarino** [comment]
I think a lot of what's needed here is documentation, but we do have a command to help generate stubs for publishing a full application in `plural create`.  

That said, there's a slew of custom resources that really need to be added to any application, the schema for deps.yaml is needed along with other stuff to make this experience as painless as possible.

**Comment by jaystary** [comment]
As we going through this process now a few times, should we provide a draft for How To / Documentation? @michaeljguarino

**Comment by michaeljguarino** [comment]
We have just set up git-based docs at https://github.com/pluralsh/documentation so you guys should be able to contribute to our docs as needed there.  Let's move this there I think
