### ISSUE TITLE
blog.plural.sh about page link broken

### ISSUE THREAD

**Issue by dblock** [pluralsh/plural#184]
## Summary

Ended up on blog.plural.sh linked from the primary.vc article.  About page link is broken. Was looking for the repo for blog.plural.sh to open this issue/fix it, but looks like it might not be OSS.

## Reproduction

![plural](https://user-images.githubusercontent.com/542335/158582364-6863de74-40e8-4ad8-be7d-86cedf8171d5.gif)

**Comment by michaeljguarino** [comment]
Hey thanks for letting us know.  It's actually a ghost site, and was probably there by default.  I swapped the link to a working page.

**Comment by dblock** [comment]
No problem! Looking forward to plural supporting https://opensearch.org :)
