### ISSUE TITLE
Unable to signup with Google -  Failed to log in, avatar is invalid

### ISSUE THREAD

**Issue by philippeboyd** [pluralsh/plural#247]
## Summary
Got an error on signup `Failed to log in avatar is invalid` after doing `plural init` and signing up with my work email (Google workspace based)

My Google avatar is nothing special, simply of picture of my face.

```
Uncaught (in promise) Error: GraphQL error: avatar is invalid
    at new t (ApolloError.ts:57:5)
    at Object.next (QueryManager.ts:225:21)
    at v (Observable.js:135:18)
    at y (Observable.js:179:3)
    at e.value (Observable.js:235:7)
    at observables.ts:12:50
    at Set.forEach (<anonymous>)
    at Object.next (observables.ts:12:19)
    at v (Observable.js:135:18)
    at y (Observable.js:179:3)
```

## Reproduction
Signup with Google with surely a picture as avatar.

![image](https://user-images.githubusercontent.com/3239656/172230669-e57c21f3-81b9-4d74-9f05-cf1bffb8063d.png)

## Plural UI/UX Issue Screenshots
![image](https://user-images.githubusercontent.com/3239656/172230359-eed97dcc-a57e-47c9-b212-45fcb1b70215.png)

**Comment by avaidyanatha** [comment]
Thanks for finding this @philippeboyd! We'll get a fix out very shortly.

**Comment by michaeljguarino** [comment]
Could I possibly get the image url for your avatar?  We'll disable syncing avatars as a quick unblock, but it would be super helpful to see the file that's causing the issue.  I wonder if it's as simple as we need to add another extension to our whitelist

**Comment by michaeljguarino** [comment]
Woops didn't mean for that PR to necessarily close the issue

**Comment by philippeboyd** [comment]
@michaeljguarino here's the avatar URL after doing an OAuth test on my end
https://lh3.googleusercontent.com/a-/AOh14GgvlOKQ27-Si3tjB4E4ft12lb3S6zrYcCRsIk_b=s100
