### ISSUE TITLE
Typo in README.md CLI screenshot

### ISSUE THREAD

**Issue by jjuanramos** [pluralsh/plural#272]
Hey all!
Just stumbled across plural and it looks super interesting! While I was reading the README.md I saw that the [CLI screenshot](https://github.com/pluralsh/plural/blob/master/www/public/plural-cli.png) contains a typo. It says "sueprset" where it should go "superset".

Wanted to make you aware of this :smile: 

Have a great day!

**Comment by samweaver** [comment]
Hey @jjuanramos thanks so much for reporting, we just fixed this up 🙏  Appreciate the issue! Is there anything else we can do? How are you getting on with Plural?
