### ISSUE TITLE
www.plural.sh 502

### ISSUE THREAD

**Issue by xunfeng1980** [pluralsh/plural#422]
## Additional Info about Your Environment

---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.

**Comment by michaeljguarino** [comment]
Thanks for the report, it's due to an issue with webflow's ssl configuration we're trying to troubleshoot

**Comment by michaeljguarino** [comment]
Here's the webflow support issue we're trying to get prioritized to fix it: https://discourse.webflow.com/t/webflow-ssl-error-when-partial-hosted-behing-nginx/214222

**Comment by michaeljguarino** [comment]
Ok we've found a workaround until the root cause with webflow can be resolved

**Comment by xunfeng1980** [comment]
good job,it work.
